# Generated by Django 3.2 on 2022-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorizer_app_id', models.CharField(max_length=64, verbose_name='公众号授权ID')),
                ('user_open_id', models.CharField(max_length=64, verbose_name='互动粉丝ID')),
                ('end_date', models.PositiveIntegerField(help_text='互动时间+48小时', verbose_name='互动戒指时间戳')),
            ],
        ),
    ]
