# Generated by Django 3.2 on 2022-06-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220513_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.IntegerField(choices=[(1, 'component_verify_ticket')], verbose_name='类型')),
                ('value', models.CharField(max_length=256, verbose_name='值')),
                ('period', models.PositiveIntegerField(verbose_name='过期时间')),
            ],
        ),
    ]
